"""``question_answer`` consumer: question captures → answered notes
(spec 06 §3.3).

Trigger TIGHTENED per B9: explicit tag ``question``/``q`` (case-insensitive,
from PARSED frontmatter via the shared module — never a hand-rolled
re-parse). The interrogative heuristic (``?`` in <500 chars, leading
interrogative word) is kept but opt-in: ``heuristic_detection = false``
default.

Decisions this seat made where doc 06 is silent (reference implementation:
``../organize/scripts/automation/consumers/question_answer.py``; its
section-B defects are NOT ported):

* **No ``processing_status`` write-back.** ``learn`` marks its sources
  (06 §3.2 mandates it), but this consumer's scope is
  ``capture/raw_capture``, where ``processing_status: raw`` is load-bearing:
  it is how the plugin's default session query finds unorganized captures
  (03 §2/§7, ``index.unorganized_captures``). Overwriting it here would
  silently hide answered captures from the organize UI. Idempotency comes
  instead from the runner's hash checkpoint plus deterministic output names
  (below), which is sufficient and destroys nothing.
* **Deterministic output names, same rule as ``learn``.** Answers land at
  ``<answers_dir>/<YYYY-MM-DD>-<question-slug>.md`` and are REPLACED on a
  rerun rather than piling up ``-1,-2,…``. Ownership is
  ``source_capture == this note`` AND the H1 still being this question, so
  a same-slug file from another capture — or one whose question the user
  rewrote — is never clobbered; it gets a source-derived suffix instead.
* **Partial answers are an ERROR, not a partial success.** With N
  questions, any unanswered one leaves the note incomplete, so the result
  is ERROR (not checkpointed ⇒ retried next run). The retry is safe
  precisely because the output names are deterministic: it overwrites its
  own files instead of duplicating them. An ``LLMUnavailable`` aborts the
  remaining questions immediately — the host is down, and hammering it
  five times per note only slows the run.
* **B10 fixed** (title/alias handling) and every frontmatter read goes
  through the shared module, which is the direct cure for B9's hand-rolled
  parse that swept ``aliases``/``sources`` in as tags.
"""

from __future__ import annotations

import hashlib
import logging
import re
from collections.abc import Callable, Mapping
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from organize_core import fileops, frontmatter
from organize_core.config import ConsumerConfig
from organize_core.consumers.base import (
    Consumer,
    ConsumerResult,
    NotePayload,
    RunContext,
    Status,
    register,
)
from organize_core.errors import ConfigError, LLMError, LLMUnavailable

LOG = logging.getLogger(__name__)

#: Research-assistant system prompt (06 §3.3) — note the explicit
#: say-so-rather-than-guess clause, which is the whole point of the prompt.
SYSTEM_PROMPT = (
    "You are a knowledgeable research assistant. Answer the question thoroughly but "
    "concisely. Include specific facts, numbers, and sources where possible. "
    "Structure your answer with clear paragraphs. "
    "If you're unsure about something, say so explicitly rather than guessing."
)

DISCLAIMER = (
    "*Answer generated by AI from a captured question. "
    "Verify important claims independently.*"
)

#: Leading-interrogative pattern shared by the (opt-in) trigger heuristic and
#: question extraction.
_INTERROGATIVE_RE = re.compile(r"^(?:what|why|how|when|where|who|which)\b", re.IGNORECASE)

#: The wider set the heuristic trigger accepts — kept verbatim from the live
#: consumer so turning ``heuristic_detection`` on restores today's behavior
#: exactly, no more and no less (06 §3.3).
_HEURISTIC_OPENERS_RE = re.compile(
    r"^(?:what|why|how|when|where|who|which|can|does|is|are|should|would|could"
    r"|i want to know|i'm wondering|i wonder|explain|tell me)\b",
    re.IGNORECASE,
)

_CONTENT_HEADING_RE = re.compile(r"^##\s*Content\s*\n?", re.IGNORECASE)
_DATED_PREFIX_RE = re.compile(r"^\d{4}-\d{2}-\d{2}-")
_H1_RE = re.compile(r"^#\s+(.*)$", re.MULTILINE)

_MISSING = object()


def _utc_now() -> datetime:
    """Single clock read for the whole module (tests monkeypatch this)."""
    return datetime.now(UTC)


# --- option plumbing --------------------------------------------------------


def _as_str(value: Any, key: str) -> str:
    if not isinstance(value, str):
        raise ConfigError(f"{key} must be a string, got {type(value).__name__}")
    return value


def _as_bool(value: Any, key: str) -> bool:
    if not isinstance(value, bool):
        raise ConfigError(f"{key} must be true or false, got {type(value).__name__}")
    return value


def _as_int(value: Any, key: str) -> int:
    if isinstance(value, bool) or not isinstance(value, int):
        raise ConfigError(f"{key} must be an integer, got {type(value).__name__}")
    if value < 1:
        raise ConfigError(f"{key} must be at least 1")
    return value


def _as_float(value: Any, key: str) -> float:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise ConfigError(f"{key} must be a number, got {type(value).__name__}")
    return float(value)


def _as_str_list(value: Any, key: str) -> list[str]:
    if isinstance(value, str):
        return [value]
    if not isinstance(value, list) or any(not isinstance(item, str) for item in value):
        raise ConfigError(f"{key} must be a list of strings")
    return list(value)


def _coerce_options(
    consumer: ConsumerConfig,
    schema: Mapping[str, tuple[Any, Callable[[Any, str], Any]]],
) -> dict[str, Any]:
    """Validate ``consumer.options`` (spec 03 §1: every key honored or a
    loud failure NAMING it). Pure — no I/O (06 §1, the B2 fix)."""
    unknown = sorted(key for key in consumer.options if key not in schema)
    if unknown:
        raise ConfigError(
            f"consumers.{consumer.name}: unknown option(s) {', '.join(unknown)}",
            hint="valid options: " + ", ".join(sorted(schema)),
        )
    resolved: dict[str, Any] = {}
    for key, (default, coerce) in schema.items():
        raw = consumer.options.get(key, _MISSING)
        if raw is _MISSING:
            resolved[key] = default() if callable(default) else default
        else:
            resolved[key] = coerce(raw, f"consumers.{consumer.name}.{key}")
    return resolved


# --- small shared helpers ---------------------------------------------------


def _field_list(payload: NotePayload, key: str) -> list[Any]:
    return frontmatter.Frontmatter(fields=dict(payload.frontmatter or {})).get_list(key)


def _tags(payload: NotePayload) -> set[str]:
    """Frontmatter tags, casefolded, via the shared coercion. This single
    line is the B9 fix: the old code re-parsed the YAML by hand and swept
    ``aliases``/``sources``/``modalities`` entries in as tags."""
    return {str(tag).strip().casefold() for tag in _field_list(payload, "tags") if str(tag).strip()}


def _is_no_ai(payload: NotePayload) -> bool:
    doc = frontmatter.Document(
        frontmatter=frontmatter.Frontmatter(fields=dict(payload.frontmatter or {})),
        body="",
    )
    return frontmatter.is_no_ai(doc)


def _slugify(text: str, limit: int) -> str:
    safe = re.sub(r"[^\w\s-]", "", str(text)).strip()[:limit]
    safe = re.sub(r"\s+", "-", safe).lower()
    return safe or "untitled"


def _vault_relative(path: Path, root: Path) -> str:
    """Vault-relative POSIX path, tolerating symlinked scan dirs (08 §B18)."""
    for base, target in ((root, path), (root.resolve(), path.resolve())):
        try:
            return target.relative_to(base).as_posix()
        except ValueError:
            continue
    return path.as_posix()


def _discriminator(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()[:8]


def _read_document(path: Path) -> frontmatter.Document | None:
    try:
        return frontmatter.load_file(path)
    except (OSError, ValueError, frontmatter.FrontmatterError):
        LOG.debug("question_answer: could not read %s", path, exc_info=True)
        return None


def _first_h1(body: str) -> str:
    match = _H1_RE.search(body or "")
    return match.group(1).strip() if match else ""


def _slug_matches(directory: Path, slug: str) -> list[Path]:
    try:
        return sorted(
            path
            for path in directory.glob(f"*-{slug}*.md")
            if _DATED_PREFIX_RE.match(path.name) and path.is_file()
        )
    except OSError:  # pragma: no cover - unreadable directory
        return []


def _resolve_output_path(
    directory: Path,
    *,
    slug: str,
    stamp: str,
    owns: Callable[[frontmatter.Document], bool],
    discriminator: str,
) -> tuple[Path, list[Path]]:
    """(target, stale) — see ``learn._resolve_output_path``; same rule:
    replace this source's own prior output, never a third party's."""
    target = directory / f"{stamp}-{slug}.md"
    stale: list[Path] = []
    foreign_at_target = False
    for path in _slug_matches(directory, slug):
        doc = _read_document(path)
        if doc is not None and owns(doc):
            stale.append(path)
        elif path == target:
            foreign_at_target = True
    if foreign_at_target:
        target = directory / f"{stamp}-{slug}-{discriminator}.md"
    return target, [path for path in stale if path != target]


def _remove_stale(paths: list[Path]) -> None:
    for path in paths:
        try:
            path.unlink()
        except OSError:  # pragma: no cover - permissions/races only
            LOG.warning("question_answer: could not remove superseded file %s", path)
        else:
            LOG.info("question_answer: replaced superseded file %s", path)


@register("question_answer")
class QuestionAnswerConsumer(Consumer):
    uses_llm = True  # no-ai notes centrally excluded (02)

    OPTION_SCHEMA: dict[str, tuple[Any, Callable[[Any, str], Any]]] = {
        # 06 §3.3 names the trigger tags "question"/"q"; the live config key
        # is the singular `marker_tag`, so both are honored: the trigger set
        # is {marker_tag} ∪ marker_tag_aliases.
        "marker_tag": ("question", _as_str),
        "marker_tag_aliases": (lambda: ["q"], _as_str_list),
        "heuristic_detection": (False, _as_bool),  # 08 §B9 — OFF by default
        "heuristic_max_chars": (500, _as_int),
        "max_questions": (5, _as_int),
        "answers_dir": ("resources/answers", _as_str),
        "flashcard_review_dir": ("resources/flashcards/review", _as_str),
        "deck": ("Reading::Questions", _as_str),
        "card_tags": (lambda: ["question-answer", "captured-question"], _as_str_list),
        "llm_timeout_seconds": (90.0, _as_float),
    }

    def __init__(self, config: ConsumerConfig) -> None:
        super().__init__(config)
        opts = _coerce_options(config, self.OPTION_SCHEMA)

        markers = [opts["marker_tag"], *opts["marker_tag_aliases"]]
        self.marker_tags: set[str] = {m.strip().casefold() for m in markers if m.strip()}
        if not self.marker_tags:
            raise ConfigError(
                f"consumers.{config.name}.marker_tag must not be empty",
                hint="the explicit-tag trigger is what keeps this consumer from "
                "answering everything that contains a '?' (spec 08 §B9).",
            )
        self.heuristic_detection: bool = opts["heuristic_detection"]
        self.heuristic_max_chars: int = opts["heuristic_max_chars"]
        self.max_questions: int = opts["max_questions"]
        self.answers_dir: str = opts["answers_dir"].strip("/")
        self.review_dir: str = opts["flashcard_review_dir"].strip("/")
        self.deck: str = opts["deck"]
        self.card_tags: list[str] = opts["card_tags"]
        self.llm_timeout_seconds: float = opts["llm_timeout_seconds"]

    # --- trigger ----------------------------------------------------------

    def should_process(self, payload: NotePayload) -> bool:
        if payload.path.suffix != ".md":
            return False
        if self.marker_tags & _tags(payload):
            return True
        if not self.heuristic_detection:
            # 08 §B9: the interrogative heuristic produced 874 answer files
            # of mostly noise. It stays implemented, and stays OFF.
            return False
        return self._looks_like_question(payload.content or "")

    def _looks_like_question(self, content: str) -> bool:
        """The opt-in heuristic, verbatim in behavior: a '?' within the first
        lines when they are short, or a leading interrogative (06 §3.3)."""
        lines = [
            line.strip()
            for line in content.split("\n")
            if line.strip() and not line.startswith("#")
        ]
        if not lines:
            return False
        main_text = " ".join(lines[:3]).lower()
        if "?" in main_text and len(main_text) < self.heuristic_max_chars:
            return True
        return bool(_HEURISTIC_OPENERS_RE.match(main_text))

    # --- steps (unit-test targets) ---------------------------------------

    def extract_questions(self, payload: NotePayload) -> list[str]:
        """Up to max_questions (5): lines ending ``?`` or starting with an
        interrogative; else the whole body (06 §3.3)."""
        questions: list[str] = []
        for raw in (payload.content or "").split("\n"):
            line = raw.strip()
            if not line or line.startswith("#") or line.startswith("---"):
                continue
            if line.endswith("?") or _INTERROGATIVE_RE.match(line):
                questions.append(line)

        if not questions:
            whole = _CONTENT_HEADING_RE.sub("", (payload.content or "").strip()).strip()
            if whole:
                questions.append(whole)

        return questions[: self.max_questions]

    def answer(self, question: str, ctx: RunContext) -> str:
        """Ollama /api/generate, temp 0.3, num_predict 1024, 90 s, the
        research-assistant system prompt (says-so-explicitly rule)
        (06 §3.3). LLM failures ⇒ ERROR result upstream, retried."""
        if ctx.llm is None:
            raise LLMUnavailable(
                "no LLM client available — questions cannot be answered",
                hint="Configure [llm] (backend + host/model) or disable "
                f"consumers.{self.config.name}.",
            )
        response = ctx.llm.generate(
            question,
            system=SYSTEM_PROMPT,
            json_mode=False,
            temperature=0.3,
            max_tokens=1024,
            timeout_seconds=self.llm_timeout_seconds,
        )
        text = (response.text or "").strip()
        if not text:  # pragma: no cover - the client already rejects empties
            raise LLMError("LLM returned an empty answer")
        return text

    def write_answer_note(
        self,
        payload: NotePayload,
        question: str,
        answer: str,
        ctx: RunContext,
    ) -> str:
        """``resources/answers/<date>-<slug>.md`` with the specced
        frontmatter (tags [ai-generated, question-answer], source_capture),
        body = question H1 + answer + verify-independently disclaimer +
        [[wikilink]] to source; plus a tier-2 flashcard in
        flashcards/review with deck Reading::Questions (06 §3.3)."""
        root = Path(ctx.config.vault.root)
        source_rel = _vault_relative(payload.path, root)
        stamp = _utc_now().strftime("%Y-%m-%d")
        slug = _slugify(question[:40], 40)

        def owns(doc: frontmatter.Document) -> bool:
            fields = doc.frontmatter.fields if doc.frontmatter else {}
            return (
                str(fields.get("source_capture") or "") == source_rel
                and _first_h1(doc.body) == question
            )

        target, stale = _resolve_output_path(
            root / self.answers_dir,
            slug=slug,
            stamp=stamp,
            owns=owns,
            discriminator=_discriminator(f"{source_rel}\n{question}"),
        )

        fields: dict[str, Any] = {
            "id": target.stem,
            "tags": ["ai-generated", "question-answer"],
            "created_date": stamp,
            "last_edited_date": stamp,
            "source_capture": source_rel,
        }
        body = (
            f"\n# {question}\n\n{answer}\n\n---\n\n"
            f"{DISCLAIMER}\n"
            f"*Source capture: [[{payload.path.stem}]]*\n"
        )
        fileops.atomic_write(
            target,
            frontmatter.serialize(
                frontmatter.Document(
                    frontmatter=frontmatter.Frontmatter(fields=fields), body=body
                )
            ),
        )
        _remove_stale(stale)

        self._write_flashcard(payload, question, answer, ctx, stamp=stamp, slug=slug)
        return str(target)

    def _write_flashcard(
        self,
        payload: NotePayload,
        question: str,
        answer: str,
        ctx: RunContext,
        *,
        stamp: str,
        slug: str,
    ) -> str:
        """The tier-2 companion card (06 §3.3): the user writes their own
        answer before revealing the model's."""
        root = Path(ctx.config.vault.root)
        source_rel = _vault_relative(payload.path, root)

        def owns(doc: frontmatter.Document) -> bool:
            fields = doc.frontmatter.fields if doc.frontmatter else {}
            return (
                str(fields.get("source_note") or "") == source_rel
                and str(fields.get("question") or "") == question
            )

        target, stale = _resolve_output_path(
            root / self.review_dir,
            slug=f"q-{slug}",
            stamp=stamp,
            owns=owns,
            discriminator=_discriminator(f"{source_rel}\n{question}"),
        )

        fields: dict[str, Any] = {
            "article": "Captured Question",
            "author": "me",
            "source_note": source_rel,
            "question": question,
            "generated": stamp,
            "status": "review",
            "deck": self.deck,
            "cards_generated": 1,
        }
        body = (
            "\n# Cards: Captured Question\n"
            "\n## Card 1 [tier2_conceptual]\n"
            f"\n**Q:** {question}\n"
            "\n**A:** *[Write your answer here before reading below]*\n"
            "\n<details><summary>Model answer (click after writing yours)</summary>\n"
            f"\n{answer}\n"
            "\n</details>\n"
            f"\nTags: {', '.join(self.card_tags)}\n"
        )
        fileops.atomic_write(
            target,
            frontmatter.serialize(
                frontmatter.Document(
                    frontmatter=frontmatter.Frontmatter(fields=fields), body=body
                )
            ),
        )
        _remove_stale(stale)
        return str(target)

    # --- orchestration ----------------------------------------------------

    def handle(self, payload: NotePayload, ctx: RunContext) -> ConsumerResult:
        path = payload.path

        # Defence in depth behind the runner's central uses_llm guard (02).
        if _is_no_ai(payload):
            LOG.warning("question_answer: refusing no-ai note %s", path)
            return ConsumerResult(Status.SKIP, "no-ai: true — LLM tooling refuses this note")

        questions = self.extract_questions(payload)
        if not questions:
            return ConsumerResult(Status.SKIP, "no questions found")

        if ctx.dry_run:
            return ConsumerResult(
                Status.SUCCESS,
                f"would answer {len(questions)} question(s)",
                {"dry_run": True, "questions_found": len(questions)},
            )

        written: list[str] = []
        failures: list[str] = []
        for question in questions:
            try:
                answer = self.answer(question, ctx)
            except LLMUnavailable as exc:
                # The backend is down: stop here rather than repeating the
                # same failure for every remaining question (06 §6).
                LOG.warning("question_answer: LLM unavailable for %s: %s", path, exc)
                failures.append(str(exc))
                break
            except LLMError as exc:
                LOG.warning(
                    "question_answer: could not answer %r from %s: %s",
                    question[:60],
                    path,
                    exc,
                )
                failures.append(str(exc))
                continue

            try:
                written.append(self.write_answer_note(payload, question, answer, ctx))
            except OSError as exc:
                LOG.error("question_answer: could not write answer for %s: %s", path, exc)
                failures.append(str(exc))

        answered = len(written)
        metadata = {
            "questions_found": len(questions),
            "answered": answered,
            "answer_files": written,
        }
        if answered == len(questions) and not failures:
            LOG.info("question_answer: answered %d question(s) from %s", answered, path)
            return ConsumerResult(
                Status.SUCCESS, f"answered {answered}/{len(questions)} questions", metadata
            )

        # Partial (or total) failure ⇒ ERROR: never checkpointed, retried
        # next run, and the retry overwrites its own deterministic outputs
        # rather than duplicating them.
        return ConsumerResult(
            Status.ERROR,
            f"answered {answered}/{len(questions)} questions: {failures[0] if failures else ''}",
            metadata,
        )
