name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Install Neovim
      uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: v0.9.0

    - name: Install dependencies
      run: |
        git clone --depth 1 https://github.com/nvim-lua/plenary.nvim
        git clone --depth 1 https://github.com/nvim-telescope/telescope.nvim
        git clone --depth 1 https://github.com/MunifTanjim/nui.nvim

    - name: Create test directories
      run: |
        mkdir -p tests/fixtures/vault/{projects,areas,resources,archives,capture/raw_capture}
        mkdir -p tests/output

    - name: Run tests
      run: |
        nvim --headless -u tests/minimal_init.lua -c "lua require('plenary.test_harness').test_directory('tests/', {minimal_init = 'tests/minimal_init.lua', sequential = true})" -c "quit"
